### ISSUE TITLE
系统更新后视频列表滑动严重卡顿掉帧

### ISSUE THREAD

**Issue by MisakaSakura** [re-ovo/iwara4a#13]
设备：一加8t
系统：color os12
屏幕刷新率：120hz
描述：更新cos12第二版后视频列表滑动严重掉帧，平均帧率只有不到40帧，波动明显，目前仅发现iwara存在此问题其他应用均无问题

**Comment by re-ovo** [comment]
我没有你这手机我也没法测试啊

**Comment by MisakaSakura** [comment]
@re-ovo 有没有调试版抓个log:disappointed_relieved:

**Comment by re-ovo** [comment]
试试新版本

**Comment by re-ovo** [comment]
@MisakaSakura

**Comment by MisakaSakura** [comment]
@re-ovo 新版刷新率正常了，但是还是有点掉帧，可能是优化问题吧，不影响正常使用了
