### ISSUE TITLE
希望添加后台卡片屏蔽预览功能

### ISSUE THREAD

**Issue by sertwen** [re-ovo/iwara4a#14]
谨防社死
![Screenshot_Quickstep_20211221-173508](https://user-images.githubusercontent.com/56821010/146906821-8835a2ba-4ee4-48f8-a3c9-61ed6b5f9480.png)
![Screenshot_EhViewer_20211221-164040](https://user-images.githubusercontent.com/56821010/146906434-f49d7011-cfed-4473-b330-89bd16b8441c.png)

**Comment by re-ovo** [comment]
目前代码有点拉跨，等着iwara迁移到新网站然后我重写app呢
