### ISSUE TITLE
A build failure caused by the version of Android Support Plugin

### ISSUE THREAD

**Issue by Xiue233** [re-ovo/iwara4a#15]
After I clone this project, I try to build it but get a warning ”This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.“
 However, I have used the latest version of AS Canary .
"Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
"
  Please tell me which version do you use.

**Comment by re-ovo** [comment]
Android Studio Chipmunk | 2021.2.1 Canary 7

**Comment by Xiue233** [comment]
Thank you very much.
