### ISSUE TITLE
从1.35版本开始，挂梯子也无法登陆和加载界面

### ISSUE THREAD

**Issue by Wjwr123** [re-ovo/iwara4a#40]
从1.35版本开始，挂上梯子也无法登陆、无法加载内容，显示ERROR
但1.35之前的版本都可以正常使用。
梯子确定无问题，可正常登录使用网页版iwara。

![Screenshot_2022-05-04-23-48-44-324_com rerere iwara4a](https://user-images.githubusercontent.com/102220555/166720212-cad9c3ac-5e40-4605-a149-b047a7209df3.jpg)
裸连偶尔能加载成功，但无法播放视频。

**Comment by VoidxHoshi** [comment]
应该是DoH的问题（i站只是简单的dns污染）
DoH就能直连登录i站，但是部分地区视频加载体验很差（虽然我这里很好）

**Comment by re-ovo** [comment]
![image](https://user-images.githubusercontent.com/21152113/166868750-1f0ebccd-e4b8-4519-b7fa-67e12d0beb55.png)

**Comment by re-ovo** [comment]
下个版本会默认关闭DoH

**Comment by VoidxHoshi** [comment]
> 下个版本会默认关闭DoH, 用户可以自行开启

目前DoH只套在了登录等功能上，请问能否也套在对视频域名的解析上呢？
如果没时间或不想实现的话，请问下视频域名解析处理在代码大概的文件位置，我自己修改代码编译
谢谢了

**Comment by re-ovo** [comment]
> > 下个版本会默认关闭DoH, 用户可以自行开启
> 
> 目前DoH只套在了登录等功能上，请问能否也套在对视频域名的解析上呢？ 如果没时间或不想实现的话，请问下视频域名解析处理在代码大概的文件位置，我自己修改代码编译 谢谢了

新开个issue

**Comment by VoidxHoshi** [comment]
> > > 下个版本会默认关闭DoH, 用户可以自行开启
> > 
> > 
> > 目前DoH只套在了登录等功能上，请问能否也套在对视频域名的解析上呢？ 如果没时间或不想实现的话，请问下视频域名解析处理在代码大概的文件位置，我自己修改代码编译 谢谢了
> 
> 新开个issue

OK
