### ISSUE TITLE
视频直连访问加速

### ISSUE THREAD

**Issue by heheha-bit** [re-ovo/iwara4a#42]
是否可以将视频解析的域名列表解析的ip强制指向Cloudflare CDN，这样的话可以借助CDN加速直连视频访问，Cloudflare CDN的ip的相关项目在https://github.com/XIU2/CloudflareSpeedTest这个项目中有提及，经目前测试其方法可行。

我得出的iwara的视频播放相关的域名为：
 www.iwara.tv
ecchi.iwara.tv
 i.iwara.tv//以上是访问网站时的
 adm.shinobi.jp//这个是获取视频列表的
  sukone.iwara.tv//以下是视频资源的
 uni.iwara.tv
  miki.iwara.tv
 ruko.iwara.tv
  hime.iwara.tv
  mikoto.iwara.tv
 yukari.iwara.tv
 cul.iwara.tv
 merli.iwara.tv 
 aku.iwara.tv
 xin.iwara.tv
 uta.iwara.tv
 hime.iwara.tv
 momo.iwara.tv

**Comment by re-ovo** [comment]
i站并没有使用cloudflare cdn

**Comment by VoidxHoshi** [comment]
I站如果使用了cf家的cdn就不会这么小霸王服务器了
😄

**Comment by heheha-bit** [comment]
可是将iwara请求指向cloudflare cdn解析的确是可以，比如我将本地的hosts更改强制将域名解析向cloudflare cdn的104.18.130.82确实可以达到全速直连的

**Comment by heheha-bit** [comment]
但是使用cloudflare cdn代理自动指向又不行，我也搞不清这是啥玄学了

**Comment by heheha-bit** [comment]
我在手机上做了同样的实验，将手机上的hosts更改为cloudflare cdn的公开ip段，也可以实现正确解析视频

**Comment by VoidxHoshi** [comment]
> 但是使用cloudflare cdn代理自动指向又不行，我也搞不清这是啥玄学了

是那个什么3proxy吗？i站的视频域名都没挂cf cdn，当然加不了速。那个功能只是用来选最好的cf cdn ip
指向cf cdn ip就能加速？可能i站注册过cf的cdn服务后来又注销了，域名还在cdn list里？感觉cf不会出这种问题吧

**Comment by heheha-bit** [comment]
> > 但是使用cloudflare cdn代理自动指向又不行，我也搞不清这是啥玄学了
> 
> 是那个什么3proxy吗？i站的视频域名都没挂cf cdn，当然加不了速。那个功能只是用来选最好的cf cdn ip 指向cf cdn ip就能加速？可能i站注册过cf的cdn服务后来又注销了，域名还在cdn list里？感觉cf不会出这种问题吧

之前我试了用3proxy是不行的，只能hosts强制更改域名解析ip为cf cdn 公开的ip段内ip，我也不知道咋做到可以访问i站的

**Comment by heheha-bit** [comment]
> > 但是使用cloudflare cdn代理自动指向又不行，我也搞不清这是啥玄学了
> 
> 是那个什么3proxy吗？i站的视频域名都没挂cf cdn，当然加不了速。那个功能只是用来选最好的cf cdn ip 指向cf cdn ip就能加速？可能i站注册过cf的cdn服务后来又注销了，域名还在cdn list里？感觉cf不会出这种问题吧

我刚在cloudflare cdn的确找到了i站的加速ip

**Comment by VoidxHoshi** [comment]
> > > 但是使用cloudflare cdn代理自动指向又不行，我也搞不清这是啥玄学了
> > 
> > 
> > 是那个什么3proxy吗？i站的视频域名都没挂cf cdn，当然加不了速。那个功能只是用来选最好的cf cdn ip 指向cf cdn ip就能加速？可能i站注册过cf的cdn服务后来又注销了，域名还在cdn list里？感觉cf不会出这种问题吧
> 
> 我刚在cloudflare cdn的确找到了i站的加速ip,好像是第三方做的加速，不是i站官方做的，指向的是i的的另一个ip，可能有人对i站做了重定向转发，然后在cloudflare cdn上挂了加速。

well
我试了一下，还真的可以
3proxy有用的前提是域名先通过CNAME被解析到cf cdn ip，然后选最好的IP
而I站没有配置这个，所以当然没用
但是强行解析到指定cf cdn ip，的确可以加速
