### ISSUE TITLE
查看喜欢列表时无下行流量

### ISSUE THREAD

**Issue by woshikedayaa** [re-ovo/iwara4a#60]
### 环境
>机场节点:圣荷西，香港
>设备:小新pad 2020 4+64
>网络环境:wifi

### 描述
查看喜欢列表时 客户端一直加载中 然后我查看了下行流量 为0~1k/s 我再次尝试了香港的节点，重启客户端 依然如此 加载不了 最后会显示加载失败
### 复现
点击喜欢 就会一直转圈

**Comment by re-ovo** [comment]
有什么即时通讯联系方式，这个需要打印日志复现

**Comment by woshikedayaa** [comment]
我q 3220465418
