### ISSUE TITLE
关于登录问题

### ISSUE THREAD

**Issue by KawaiiTamako** [re-ovo/iwara4a#67]
![Screenshot_2022-06-06-19-22-15-643_com rerere iwa](https://user-images.githubusercontent.com/51044119/172151473-d6e34014-2c54-4dbb-86d3-00cd503f9677.jpg)
![Screenshot_2022-06-06-19-20-26-885_com rerere iwa](https://user-images.githubusercontent.com/51044119/172151486-54a84d77-e807-4802-ba5d-90117dba9255.jpg)

**Comment by re-ovo** [comment]
用浏览器能登录上吗

**Comment by KawaiiTamako** [comment]
> 我测试登录没有问题，你用的是最新版吗？

1.40.0版本 难道是因为MIUI13？

**Comment by re-ovo** [comment]
不应该的

**Comment by re-ovo** [comment]
我也是MIUI13,没有问题

**Comment by KawaiiTamako** [comment]
> 我也是MIUI13,没有问题

我用流量没出这个错误了

**Comment by KawaiiTamako** [comment]
> 我也是MIUI13,没有问题

好吧，还是这样。刚刚说我密码错误还以为可以了，很奇怪...
