### ISSUE TITLE
LocalOverScrollConfiguration编译时找不到，此实验类已被谷歌删除

### ISSUE THREAD

**Issue by s949492225** [re-ovo/iwara4a#80]
LazyStaggeredGrid这文件里用了下面这个类
androidx.compose.foundation.gestures.LocalOverScrollConfiguration

这个是实验性api，看官方文档已经把这个删除了，导致了编译时找不到

**Comment by re-ovo** [comment]
这个还在的，只是换了个包

**Comment by s949492225** [comment]
master版本我确实报这个错，回头我找下迁到到哪个库里

**Comment by re-ovo** [comment]
AS应该会提示重新导包吧😂

**Comment by s949492225** [comment]
![image](https://user-images.githubusercontent.com/7496283/174946593-2c17e83d-1342-4221-ad64-acf9ca0782f0.png)
木有，完全就是找到那种 😊

**Comment by s949492225** [comment]
我找到了，迁移到了foundation 这里面
import androidx.compose.foundation.gestures.LocalOverScrollConfiguration  这个是找不到的
import androidx.compose.foundation.LocalOverscrollConfiguration 这个是新的
OverScroll变成了Overscroll ，S变小写了,这可真坑呀

**Comment by s949492225** [comment]
#81 
pr fix it
