### ISSUE TITLE
播放界面的改进

### ISSUE THREAD

**Issue by woshikedayaa** [re-ovo/iwara4a#94]
## 手势控制
手势控制现在在我平板上调动速度很慢 通常拖很长才前进或者后退几秒   
希望可以自己控制手势速率或者根据屏幕适配
## 加载进度条
加载进度条和播放进度条对不齐
## 网速显示
希望在加载转圈的下面显示实时网速

**Comment by woshikedayaa** [comment]
在提个小小的bug   
在1.40.1版本手势没法倒退进度条

**Comment by re-ovo** [comment]
加载进度条目前由于设计风格问题没法很好的和进度条混合在一起，以后再说吧

**Comment by re-ovo** [comment]
网速显示暂时不实现

**Comment by re-ovo** [comment]
bug已修复
